exclude: ["README.md", "Gemfile", "Gemfile.lock"]

# Site settings
title: dewafer
email: dewafer@gmail.com
description: What's this?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dewafer.github.io" # the base hostname & protocol for your site
twitter_username: dewafer
github_username:  dewafer
author: dewafer
author_url: "https://github.com/dewafer"

# Build settings
markdown: kramdown

# Enable pagination
paginate: 10
paginate_path: "blog/page:num/"

# Excerpt
excerpt_separator: "<!--more-->"